"showobjectreportextern,showvehiclereportextern,shownearestvehicles,showcontracts,updatevehicle,showobjectgroups,showobjectgroupobjects,attachobjecttogroup,detachobjectfromgroup,insertobjectgroup,deleteobjectgroup,updateobjectgroup,switchoutput,showwakeuptimers,updatewakeuptimers,getobjectfeatures,updatecontractinfo,getobjectcansignals,getobjectcanmalfunctions,getelectricvehicledata,getactiveassetcouplings,sendorderextern,senddestinationorderextern,updateorderextern,updatedestinationorderextern,insertdestinationorderextern,cancelorderextern,assignorderextern,reassignorderextern,deleteorderextern,clearordersextern,showorderreportextern,showorderwaypoints,sendtextmessageextern,cleartextmessagesextern,showmessages,sendbinarymessage,resetbinarymessages,clearbinarymessages,showdriverreportextern,insertdriverextern,updatedriverextern,deletedriverextern,showoptidriveindicator,showdrivergroups,showdrivergroupdrivers,attachdrivertogroup,detachdriverfromgroup,insertdrivergroup,deletedrivergroup,updatedrivergroup,attachdrivertovehicle,detachdriverfromvehicle,getdriverrdtrules,updatedriverrdtrules,showaddressreportextern,showaddressgroupreportextern,showaddressgroupaddressreportextern,insertaddressextern,updateAddressExtern,deleteaddressextern,attachaddresstogroupextern,detachaddressfromgroupextern,insertaddressgroupextern,deleteaddressgroupextern,showeventreportextern,acknowledgeeventextern,resolveeventextern,geteventforwardconfigs,geteventforwardconfigrecipients,inserteventforwardconfig,updateeventforwardconfig,deleteeventforwardconfig,showtripreportextern,showtripsummaryreportextern,showtracks,updatelogbook,showlogbook,showlogbookhistory,updatelogbookmode,updatelogbookdriver,showworkingtimes,showstandstills,showidleexceptions,getobjectkpis,getdriverkpis,getremainingdrivingtimeseu,getchargerconnections,showioreportextern,showaccelerationevents,showspeedingevents,showdigitalinputstatemileage,getchargerconnections,geocodeaddress,calcroutesimpleextern,showsettings,createsession,terminatesession,showaccountorderstates,updateaccountorderstate,showaccountorderautomations,updateaccountorderautomation,getaccountstatusmessages,getstatusmessages,setvehicleconfig,getvehicleconfig,setstatusmessages,setaccountstatusmessages,showusers,changepassword,insertmaintenanceschedule,updatemaintenanceschedule,deletemaintenanceschedule,showmaintenanceschedules,showmaintenancetasks,resolvemaintenancetask,getarchivedreportlist,getarchivedreport,deletearchivedreport,getreportlist,createreport,sendreportviamail,getareas,insertarea,deletearea,updatearea,getareapoints,getareaassignments,insertareaassignment,deleteareaassignment,getareaschedules,insertareaschedule,deleteareaschedule,sendauxdevicedata,getlocalauxdeviceconfig,configurelocalauxdevice,getremoteauxdeviceconfig,configureremoteauxdevice,removeremoteauxdeviceconfig,clearauxdevicedataqueue,resetauxdevicedata,insertexternalevent"




"
showObjectReportExtern,
showVehicleReportExtern,
showContracts,
showObjectGroups,
showObjectGroupObjects,
getObjectCanMalfunctions,
getElectricVehicleData,
showDriverReportExtern,
showDriverGroups,
showDriverGroupDrivers,
showAddressReportExtern,
showAddressGroupReportExtern,
showAddressGroupAddressReportExtern,
getVehicleConfig,
showUsers,
showMaintenanceSchedules,
getReportList,
getAreas,
getLocalAuxDeviceConfig," 


"
SABEVI BELFORT BETON,
SABEVI BESANCON BETON,
SABEVI BOURGOGNE BETON,
ERM LEVIER,
RM AURA - MOULIN ENVIRONNEMENT,
AXIROUTE,
MERLOT TP,
ERM BELFORT,
ERM DANNEMARIE,
RM AURA - CANTAL,
RM AURA - MOULIN TP,
RM AURA - ISERE LOIRE RHONE,
RM AURA - AIN,
SETEC,
ERM SAINT APOLLINAIRE,
ERM TROYES,
ERM VESOUL,
ERM DOLE,
SODIBE,
ERM AGT/AGTE,
ERM LABO CENTRAL,
RM AURA - REGION,
SNCTP MATERIEL,
ALL_ROGER_MARTIN,
ALL_SNCTP,



"